#!/bin/bash

# QUICK START GUIDE - Bilingual Translation Implementation
# Run this to test the implementation

echo "==============================================="
echo "🚀 BILINGUAL TRANSLATION - QUICK START"
echo "==============================================="
echo ""

echo "✅ STEP 1: Start MongoDB"
echo "   Make sure MongoDB is running on port 27017"
echo "   Command: mongod (in separate terminal)"
echo ""

echo "✅ STEP 2: Start Backend"
echo "   cd Backend"
echo "   npm install (first time only)"
echo "   npm run dev"
echo "   ⏳ Wait until you see: 'Server running on port 5000'"
echo ""

echo "✅ STEP 3: Start Frontend (new terminal)"
echo "   cd Frontend"
echo "   npm install (first time only)"
echo "   npm start"
echo "   ⏳ Wait until browser opens at localhost:3000"
echo ""

echo "✅ STEP 4: Seed Database (new terminal)"
echo "   cd Backend"
echo "   node seed.js"
echo "   ⏳ Wait for: 'Database seeded successfully!'"
echo ""

echo "✅ STEP 5: Test Bilingual Feature"
echo ""
echo "   A. Login as EMPLOYER:"
echo "      Email: priya@employer.com"
echo "      Password: password123"
echo ""
echo "   B. Post a NEW JOB:"
echo "      Title: Your Job Title (in English)"
echo "      Description: Your description (in English)"
echo "      Work Type: Select any"
echo "      Location: Any district"
echo "      Salary: Any amount"
echo "      Click: Post Job"
echo ""
echo "   C. Check Database (MongoDB Compass or mongo shell):"
echo "      Collection: jobs"
echo "      Should see fields:"
echo "        - title: (your English title)"
echo "        - titleHi: (auto-translated to Hindi)"
echo "        - description: (your English description)"
echo "        - descriptionHi: (auto-translated)"
echo ""
echo "   D. Logout and Login as WORKER:"
echo "      Email: rajesh@worker.com"
echo "      Password: password123"
echo ""
echo "   E. Browse Jobs:"
echo "      Should see your job with English title"
echo ""
echo "   F. TEST LANGUAGE TOGGLE:"
echo "      Click 🌐 Button (top right in navbar)"
echo "      Watch as everything translates to Hindi!"
echo "      • Job titles change to Hindi"
echo "      • Job descriptions change to Hindi"
echo "      • All UI text changes to Hindi"
echo ""
echo "   G. Click 🌐 Button AGAIN:"
echo "      Everything switches back to English!"
echo ""
echo "   H. Refresh Page (Ctrl+R):"
echo "      Language preference PERSISTS!"
echo "      You'll still see Hindi (or English)"
echo ""

echo "==============================================="
echo "✨ WHAT YOU'LL SEE:"
echo "==============================================="
echo ""
echo "English View:"
echo "  Job Title: Construction Helper"
echo "  Location: Location"
echo "  Salary: Salary"
echo ""
echo "Hindi View (after clicking 🌐):"
echo "  Job Title: निर्माण सहायक"
echo "  Location: जगह"
echo "  Salary: मजदूरी"
echo ""

echo "==============================================="
echo "📊 FEATURES WORKING:"
echo "==============================================="
echo ""
echo "✅ Job Title Translation"
echo "✅ Job Description Translation"
echo "✅ Work Type Translation"
echo "✅ Salary Period Translation"
echo "✅ Instant Language Switching"
echo "✅ No Page Reload Needed"
echo "✅ Preference Persists"
echo "✅ All UI Labels Translated"
echo ""

echo "==============================================="
echo "🔧 TROUBLESHOOTING:"
echo "==============================================="
echo ""
echo "❓ Jobs not translating?"
echo "   → Re-seed database: node Backend/seed.js"
echo "   → Or post a NEW job (auto-translates)"
echo ""
echo "❓ Language button not working?"
echo "   → Hard refresh: Ctrl+Shift+R"
echo "   → Check browser console (F12)"
echo ""
echo "❓ Build errors?"
echo "   → Clear node_modules: rm -rf node_modules"
echo "   → Reinstall: npm install"
echo "   → Rebuild: npm run build"
echo ""

echo "==============================================="
echo "📝 DATABASE SCHEMA:"
echo "==============================================="
echo ""
echo "Jobs collection now has:"
echo ""
echo "  title: String       ← English title"
echo "  titleHi: String     ← Hindi title (auto)"
echo "  description: String ← English description"
echo "  descriptionHi: String ← Hindi description (auto)"
echo "  ... other fields ..."
echo ""

echo "==============================================="
echo "🎉 YOU'RE READY TO GO!"
echo "==============================================="
echo ""
echo "Follow the steps above and enjoy bilingual support!"
echo ""
